- name: determine swarm status
  shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status
  tags: [swarm]


- name: Swarm master is running
  shell: "docker swarm init   --advertise-addr  {{ host_ip  }}  "
  when:  hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'] is not   defined     and  'active' not in swarm_status.stdout_lines and swarm_master is defined
  register: swarm_init
  tags: [swarm]

- name: display token(1)
  debug:
    msg: "  {{ hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'].stdout }} "  
  when:   hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'] is   defined 
  tags: [swarm]

- name: display token(1)
  debug:
    msg: "  {{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'].stdout }} "  
  when:   hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] is   defined 
  tags: [swarm]

- name: retrieve swarm manager token (1-0-1)
  command: docker swarm join-token -q manager
  when:   hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'] is not  defined 
  register:   swarm_manager_token
  tags: [swarm]

- name: retrieve swarm worker token (1-0-2)
  shell: docker swarm join-token -q worker
  when:  hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] is not  defined 
  register: swarm_worker_token
  tags: [swarm]


- name: set_fact docker_swarm_manager_token(1-1)
  set_fact:
    docker_swarm_manager_token: "{{ swarm_manager_token }}"
    mm: 1
  when:  hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'] is not  defined
  tags: [swarm]

- name: set_fact docker_swarm_manager_token(1-2)
  set_fact:
    docker_swarm_manager_token:  "{{ hostvars[groups['swarm-master'][0]]['docker_swarm_manager_token'] }} "
  when:  mm is  not   defined
  tags: [swarm]

- name: join manager nodes to cluster
  shell: "docker swarm join  --token {{ docker_swarm_manager_token.stdout }}  --advertise-addr  {{ host_ip  }}  {{ swarm_master_ip }}:2377" 
  when: mm is  not   defined  and  'active' not in swarm_status.stdout_lines and swarm_master is defined 
  tags: [swarm]


- name: set_fact docker_swarm_worker_token(1-1)
  set_fact:
    docker_swarm_worker_token: "{{ swarm_worker_token }}"
    ww: 1
  when:  hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] is not  defined
  tags: [swarm]

- name: set_fact docker_swarm_worker_token(1-2)
  set_fact:
    docker_swarm_worker_token:  "{{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] }} "
  when:  ww is  not   defined
  tags: [swarm]

- name: join worker nodes to cluster
  shell: "docker swarm  join   --token {{ docker_swarm_worker_token.stdout }}   --advertise-addr {{ host_ip  }}  {{ swarm_master_ip }}:2377" 
  when:  ww is  not   defined   and  'active' not in swarm_status.stdout_lines and not swarm_master is defined  
  tags: [swarm]  


