- name: pull an image
  docker_image:
    name: {{ calico_node_image }}:{{ calico_node_ver }}
  tags: [calico]

- name: Executable is present
  get_url:
    url: "{{ calicoctl_url }}"
    dest: /usr/bin/calicoctl
    mode: 0755

### Below is Calico sell

# - name: Is calicoctl running (shell)
#   become: true
#   become_user: root 
#   shell: 
#      " sudo ETCD_ENDPOINTS=http://{{ host_ip }}:2379 calicoctl node run --node-image=quay.io/calico/node:{{ calico_node_ver }}"
#   tags: [calico]


### Below is Calico service
- name: Calico dirctory are copied
  file: path=/etc/calico/  state=directory mode=0755
  ignore_errors: yes
  tags: [calico]

- name: Calico environment files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  tags: [calico]

- name: Calico-node service files are present
  template:
    src: "{{ calico_cfg }}"
    dest: "{{ calico_cfg_dest }}"
  tags: [calico]

- name: enable calico-node
  service:
    name: calico-node
    enabled: yes
  tags: [calico]

- name: restart calico-node
  systemd:
    name: calico-node
    state: restarted
    enabled: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [calico]